name: anom-detector

volumes:
  anom-nginx-logs:
  nextcloud-data:
  nextcloud-db:
  detector-state:
  detector-audit:
  certbot-certs:
  certbot-www:

networks:
  anom-net:
    driver: bridge

services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    networks: [anom-net]
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpw}
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: ${MYSQL_PASSWORD:-ncpw}
    volumes:
      - nextcloud-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  nextcloud:
    image: kefaslungu/hng-nextcloud:latest
    restart: unless-stopped
    networks: [anom-net]
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ncpw}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS:-localhost}
      TRUSTED_PROXIES: 0.0.0.0/0
    volumes:
      - nextcloud-data:/var/www/html
      - anom-nginx-logs:/var/log/nginx:ro

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    networks: [anom-net]
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextcloud
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - anom-nginx-logs:/var/log/nginx
      - certbot-certs:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro

  detector:
    build: ./detector
    restart: unless-stopped
    networks: [anom-net]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8081:8080"
    environment:
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    volumes:
      - anom-nginx-logs:/var/log/nginx:ro
      - detector-state:/var/lib/detector
      - detector-audit:/var/log/detector
    depends_on:
      - nginx